#!/bin/bash

pushd()
{
    builtin pushd "$@" > /dev/null
}
popd()
{
    builtin popd "$@" > /dev/null
}

## Create a new initrd.baracus
##
##

DATADIR=workload
DSTDIR=$DATADIR/initrd.dir
[ ! -z "$1" ] && INITRD_IMG=$1 
[ -z "$INITRD_IMG" ] &&  INITRD_IMG=initrd.opensuse-11.3

echo "using initrd: $INITRD_IMG"

[[ -d $DSTDIR ]] && rm -rf $DSTDIR
mkdir -p $DSTDIR
cp $DATADIR/$INITRD_IMG $DSTDIR

## Extract the image
##

pushd $DSTDIR
  mv $INITRD_IMG initrd.gz
  gzip -d initrd.gz
  cpio --quiet -id < initrd 
  rm initrd
  
  ## copy-in the baracus data
  ##
  mkdir -p usr/bin/
  BA_APPS="pxewait busybox.dban baracus.dban baracus.image baracus.mcast baracus.clone baracus.register lshw-static.B.02.15.x86 dbclient shellexec"
  for i in $BA_APPS; do
        cp ../$i usr/bin/.
  done
  cp ../busybox-1.16.1.udpcast-20100130 usr/bin/busybox.udpcast

  cp ../halt sbin/.
  cp ../dropbear sbin/.
  mkdir -p log/dban
  mkdir -p usr/share/
  cp -r ../terminfo usr/share/.
  mkdir -p etc/dropbear
  cp ../dropbear_rsa_host_key etc/dropbear
  chown root:root etc/dropbear/dropbear_rsa_host_key
  cp ../shells etc/.
  
  pushd usr
    ln -s . i386-linux-uclibc
  popd
  
  pushd sbin
    ln -s halt reboot
  popd
  
  pushd bin
    ln -s ../usr/bin/busybox.udpcast udp-receiver
    ln -s ../usr/bin/busybox.udpcast udp-sender

    APPLETS="ash cp dd dmesg echo grep ls tar date mv"
    for i in $APPLETS; do
        ln -s ../usr/bin/busybox.dban $i
    done
  popd
  
  pushd usr/bin
    APPLETS="clear dwipe sort tr wc"
    for i in $APPLETS; do
        ln -s ../../usr/bin/busybox.dban $i
    done
  popd
  
  pushd etc
    echo "root:Wvg7eFFQQVjbo:14869:0:99999:7:::" > shadow
    echo "root:x:0:0:root:/root:/usr/bin/shellexec" > tmppasswd
    grep -v "root" passwd >> tmppasswd
    mv tmppasswd passwd
  popd
  
  ## create the new image
  ##
  [ -f ../initrd.baracus ] && rm ../initrd.baracus
  find . | cpio --quiet --create --format='newc' > ../initrd.baracus
popd

pushd $DATADIR
  gzip initrd.baracus
  mv initrd.baracus.gz initrd.baracus
popd

[[ -d $DSTDIR ]] && rm -rf $DSTDIR

## complete
##
echo "initrd.baracus generation complete"
