#!/bin/bash

trap 'keeper' 2
trap 'keeper' 20

# weird that we don't ahve these in all our shells ... extract

export baracus=`cat /proc/cmdline    | sed -re 's/^.* baracus=([^ ]*).*$/\1/'`
export macaddr=`sed -re 's/^.* mac=([^ ]*).*$/\1/' /proc/cmdline`

if [ ! -f /tmp/flag ]
then
    echo "" > /tmp/flag
    echo -ne "Getting network settings via dhcp\n"
    /sbin/dhcpcd -t60 eth0
    mount -t devpts devpts /dev/pts
    sleep 5
    /sbin/dropbear -p 0.0.0.0:22 -r /etc/dropbear/dropbear_rsa_host_key

    echo "pxewait" > /tmp/sshshell

    # notify the baracus server the node is in pxewaitr
    PARAMS="mac=$mac"
    URL="http://$baracus/ba/pxewaitr?$PARAMS"
    /usr/bin/curl $URL
fi


# get the IP we were DHCP'd

export ipaddr=`/sbin/ifconfig eth0 | grep "inet addr" |sed -re 's/^.* inet addr:([^ ]*).*$/\1/'`
export chkmac=`/sbin/ifconfig eth0 | grep "HWaddr" |sed -re 's/^.* HWaddr ([^ ]*).*$/\1/'`


keeper()
{
return
}

menu()
{
echo 
echo "Local MAC: $macaddr"
if [[ "$macaddr" != "$chkmac" ]]; then
  echo "Oddly eth0 MAC is different: $chkmac"
fi
echo "Local IP:  $ipaddr"
echo "Baracus Host: $baracus"
echo "-------------------------------------"
echo "| Baracus pxewait shell             |"
echo "|                                   |"
echo "| 1 - reboot                        |"
echo "| 2 - shutdown                      |"
echo "| 3 - disconnect                    |"
echo "-------------------------------------"
}

clear
menu
while :
do
  echo -ne "> "
  read selection
  case $selection in
  1)
    echo "rebooting..."
    /sbin/reboot -f
  ;;
  2)
    echo "shutting down..."
    /sbin/halt -p -n -f
  ;;
  3)
    if [[ x"$TERM" != x"linux" ]]
    then
      echo "disconnecting..."
      exit
    else
      clear
      menu
    fi
  ;;
  8675309)
    /bin/bash
    menu
  ;;
  *)
    echo "invalid selection"
  ;;
  esac
done

