#!/bin/bash

trap 'keeper' 2
trap 'keeper' 20

keeper()
{
return
}

menu()
{
echo 
echo "Local  MAC: $macaddr"
echo "Local  IP:  $ipaddr"
echo "-------------------------------------"
echo "| Baracus pxewait shell             |"
echo "|                                   |"
echo "| 1 - reboot                        |"
echo "| 2 - disconnect                    |"
echo "-------------------------------------"
}

if [ ! -f /tmp/flag ]
then
  echo -ne "Getting network settings via dhcp\n"
  /sbin/dhcpcd -t60 eth0
  mount -t devpts devpts /dev/pts
  sleep 5
  /sbin/dropbear -p 0.0.0.0:22 -r /etc/dropbear/dropbear_rsa_host_key

  PARAMS="mac=$mac&ip=$ipaddr"
  URL="http://$baracus/ba/pxewaitr?$PARAMS"
  /usr/bin/curl $URL
fi

export ipaddr=`/sbin/ifconfig eth0 | grep "inet addr" | sed -e 's/^.*addr://' | sed -e 's/Bcast.*$//'`
export macaddr=`/sbin/ifconfig eth0 | grep "HWaddr" | sed -e 's/^.*HWaddr //'`

echo "" > /tmp/flag
clear
menu
while :
do
  echo -ne "> "
  read selection
  case $selection in
  1)
    echo "rebooting..."
    /sbin/reboot -f
  ;;
  2)
    if [[ x"$TERM" != x"linux" ]]
    then
      echo "disconnecting..."
      exit
    else
      clear
      menu
    fi
  ;;
  8675309)
    /bin/bash
  ;;
  *)
    echo "invalid selection"
  ;;
  esac
done

